# Generated by Django 4.2.27 on 2026-02-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('bsc_cs', 'B.Sc. Computer Science'), ('bsc_micro', 'B.Sc. Microbiology'), ('bsc_biochem', 'B.Sc. Biochemistry'), ('bsc_biotech', 'B.Sc. Biotechnology'), ('bsc_psy', 'B.Sc Psychology'), ('bsc_food', 'B.Sc. Food Technology'), ('bcom_ca', 'B.Com with Computer Application'), ('bcom_fin', 'B.Com Finance'), ('bcom_mark', 'B.Com Marketing'), ('bcom_coop', 'B.Com Co-operation'), ('bba', 'B.B.A.'), ('ba_eng', 'B.A English'), ('ba_eco', 'B.A Economics'), ('msc_cs', 'M.Sc Computer Science'), ('msc_biotech', 'M.Sc Biotechnology'), ('msc_micro', 'M.Sc Microbiology'), ('msc_biochem', 'M.Sc Biochemistry')], max_length=30, null=True),
        ),
    ]
