# Generated by Django 4.2.27 on 2026-02-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_customuser_address_customuser_phone_customuser_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
