# Generated by Django 4.2.27 on 2026-02-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
